language: python

python:
    - '3.6'
    - '3.7'
    - '3.8'

install:
    - pip install -e ."[dev]"

script:
    - flake8 python_project/*.py
    - flake8 test/*.py
    - pytest --cov=python_project

deploy:
    provider: pypi
    username: __token__
    password:
        secure: # TODO: Add secure token here
    on:
        tags: true
    skip_existing: true

after_success:
    - coveralls
